Postprocess
HTXDIF/cep-backend pull request #10
Opened 2022-03-31 08:48 UTC by bearpolar

Postprocessing lambda with SES

2022-04-04 05:15 UTC, madanalogy requested changes
Template looks good! Just the function handlers that might need some tweaking. You can take a look at these resources for reference:

- https://docs.aws.amazon.com/lambda/latest/dg/with-sqs-example.html
- https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

2022-04-04 05:15 UTC, madanalogy commented on src/api/update-database.js
> +  sqs.receiveMessage(queue_params, function(err, data) {
This implementation pulls the messages from the SQS queue directly. What you need to do is read the message from the event source

2022-04-04 05:15 UTC, madanalogy commented on src/api/send-email.js
> +  sqs.receiveMessage(queue_params, function(err, data) {
Similarly here

2022-04-04 05:15 UTC, madanalogy commented on template.yaml
> +            BatchSize: 10
You can see here that the queue is specified as the event source, so the messages should come from the lambda `event` parameter.

2022-04-04 10:43 UTC, bearpolar commented on src/api/update-database.js
> +  sqs.receiveMessage(queue_params, function(err, data) {
replaced sqs.receiveMessage function with SQS event source mapping for Lambda

2022-04-04 15:28 UTC, madanalogy commented on template.yaml
> +            BatchSize: 10
Actually, maybe have the function process one message at a time, so `BatchSize: 1` haha

2022-04-11 09:44 UTC, bearpolar commented on src/api/send-email.js
> +  } catch (err) { console.log("Receive Error", err); }
updated as suggested

2022-04-11 09:45 UTC, bearpolar commented on template.yaml
> +            BatchSize: 10
updated BatchSize: 1

2022-04-11 10:39 UTC, madanalogy approved these changes
LGTM

2022-04-11 10:39 UTC, merged