Linette
HTXDIF/cep-backend pull request #9
Opened 2022-03-29 09:56 UTC by Linettehtx

I added the queue for the two evidence sources as well as the queue function in the template.yaml. The code for the url_to_pdf, I have also added it inside.

2022-03-29 11:53 UTC, madanalogy commented on src/feature/urltopdf/lib/aws.js
> +const dynamodb = new AWS.DynamoDB();
the feature lambdas shouldn't be communicating with the db directly

2022-03-29 11:57 UTC, madanalogy commented on src/feature/urltopdf/index.js
> +  let filelabel = currentDateTime + "_" + url.split("//")[1].split("/", 1)[0];
Could you call `JSON.stringify(event)` only once and assign it to an object? Then you can check the object for its attributes instead of always repeatedly calling `stringify` and then `indexOf`.

2022-03-29 11:58 UTC, madanalogy commented on src/feature/urltopdf/index.js
> +  };
Response should be going out to a post processing queue. Not very sure if this is the format you want passed as the message

2022-04-04 12:27 UTC, Linettehtx commented on src/feature/urltopdf/lib/aws.js
> +const dynamodb = new AWS.DynamoDB();
I removed that portion to go to the post processing queue based on XL's post processing template

2022-04-04 12:28 UTC, Linettehtx commented on src/feature/urltopdf/index.js
> +  let filelabel = currentDateTime + "_" + url.split("//")[1].split("/", 1)[0];
I added that for the download type one, the schedule one since we may not use, I removed it.

2022-04-04 12:30 UTC, Linettehtx commented on src/feature/urltopdf/index.js
> +  };
I added a new js file to send message, update and error in a different function, not sure if it works that way. Because they all have different parameters

2022-04-04 12:31 UTC, Linettehtx commented on src/feature/urltopdf/index.js
> +    return response;
I left all returns as returns, and it will all go through the post processing queue

2022-04-04 12:32 UTC, Linettehtx commented
I havent tested whether the queue will work yet, mainly the things stated I have tried modifying it

2022-04-04 15:23 UTC, madanalogy requested changes

2022-04-04 15:23 UTC, madanalogy commented on src/feature/urltopdf/index.js
> +  let event = JSON.stringify(event.Records[0].body);
Please don't redeclare function parameters. It could cause confusion with respect to what variable you're referring to and is really not necessary. Additionally, I don't see the need for you to stringify a JSON object in code. If you need to check whether an attribute is present or not you can use a ternary operator checking for whether the attribute is truthy. You might also want to check whether the records array is null or empty

```suggestion
  if (!event.Records || event.Records.length === 0) {
    throw "No event records";
  }
  const { body } = event.Records[0];
```

2022-04-04 15:25 UTC, madanalogy commented on src/feature/urltopdf/index.js
> +  };
We can figure it out later haha no worries

2022-04-08 02:32 UTC, Linettehtx commented on template.yaml
> +            BatchSize: 10
okay can this one can change

2022-04-08 03:26 UTC, madanalogy commented on src/feature/urltopdf/index.js
> +  if (!event.uniqueId) {
All references to `event` from here and lower should be changed to `body` right? If I'm understanding it correctly

2022-04-08 07:31 UTC, Linettehtx commented on src/feature/urltopdf/index.js
> +  if (!event.uniqueId) {
yeah changed for those that will be using the body

2022-04-08 16:36 UTC, madanalogy approved these changes
Looks good let's get this merged in

2022-04-08 16:36 UTC, merged